### PR TITLE
Add support for Laravel 11

### PR DESCRIPTION
**Pull request by popjelev**

### CODE REVIEW

**Review by man0l — APPROVED** [review]
looks good for me, I've tried it since i am upgrading to laravel 11 and tested it out.

**Review by ratajski — APPROVED** [review]

**Review by kingmaker-agm — APPROVED** [review]
This **Dependency upgrade** supports the _latest Laravel version_ and it works perfectly on my project.

**Review by oyepez003 — APPROVED** [review]

**Comment by kingmaker-agm** [comment]
Thanks for making the merge @oyepez003

**Comment by kingmaker-agm** [comment]
@oyepez003 kindly add a **Tag** `v0.3.1` to the latest merge, So that it will be published into the **Packagist** and we can use it via _Composer_

**Comment by oyepez003** [comment]
> @oyepez003 kindly add a **Tag** `v0.3.1` to the latest merge, So that it will be published into the **Packagist** and we can use it via _Composer_

Done: https://github.com/yepsua/filament-rating-field/releases/tag/v0.4.0

**Pull request merged**
